---@class Config: Config.Util
local Config = {
	filetypes = {
		ui = {
			"DiffviewFiles",
			"NeogitCommitSelectView",
			"NeogitCommitView",
			"NeogitConsole",
			"NeogitDiffView",
			"NeogitGitCommandHistory",
			"NeogitLogView",
			"NeogitPopup",
			"NeogitReflogView",
			"NeogitRefsView",
			"NeogitStashView",
			"NeogitStatus",
			"NvimTree",
			"Outline",
			"PlenaryTestPopup",
			"TelescopePrompt",
			"Trouble",
			"WhichKey",
			"alpha",
			"checkhealth",
      "cmd",
			"cmp_menu",
			"dap-repl",
			"dap-view",
			"dap-view-repl",
			"dap-view-term",
			"dashboard",
			"dbout",
      "dialog",
			"fugitive",
			"gitsigns-blame",
			"grug-far",
			"help",
			"lazy",
			"lspinfo",
			"man",
			"mason",
			"minifiles",
			"minipick",
			"ministarter",
      "msg",
			"neo-tree",
			"neo-tree-popup",
			"neotest-output",
			"neotest-output-panel",
			"neotest-summary",
			"noice",
			"notify",
      "nvim-pack",
			"packer",
      "pager",
			"qf",
			"sidekick_terminal",
			"snacks_dashboard",
			"snacks_notif",
      "snacks_layout_box",
      "snacks_picker",
      "snacks_picker_input",
      "snacks_picker_list",
      "snacks_picker_preview",
			"snacks_terminal",
			"snacks_win",
			"spectre_panel",
			"startify",
			"startuptime",
			"terminal",
			"toggleterm",
			"trouble",
			"tsplayground",
			"unite",
			"wayfinder",
		},
	},
	-- stylua: ignore
	icons = {
		separator = "  ",
		dots      = "󰇘",
		prompt    = "  ",
		caret     = " ",
		multi     = " ",
		eob       = " ",
		tag       = "󰓹 ",
		fold = {
			foldclose = "",
			foldopen  = "",
			fold      = " ",
			foldsep   = " ",
		},
		dap = {
			Stopped             = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
			Breakpoint          = " ",
			BreakpointCondition = " ",
			BreakpointRejected  = { " ", "DiagnosticError" },
			LogPoint            = ".>",
		},
		diagnostics = {
			Error = " ",
			Warn  = " ",
			Hint  = " ",
			Info  = " ",
		},
		diff = {
			added    = " ",
			modified = " ",
			removed  = " ",
		},
		git = {
			staged    = " ",
			added     = "󰐕 ",
			deleted   = " ",
			ignored   = " ",
			modified  = " ",
			renamed   = " ",
			unmerged  = " ",
			untracked = " ",
		},
		task = {
			todo      = "󰄰 ",
			done      = "󰄴 ",
			active    = "󰪞 ",
			cancelled = "󱃓 ",
			important = "󰗖 ",
		},
		services = {
			copilot        = " ",
			diagnostics    = "󱤧 ",
			formatting     = "󰉼 ",
			not_persisting = " ",
			persisting     = "󰅟 ",
			treesitter     = " ",
		},
		kinds = {
			Array         = " ",
			Boolean       = "󰨙 ",
			Class         = " ",
			Codeium       = "󰘦 ",
			Collapsed     = " ",
			Color         = " ",
			Constant      = "󰏿 ",
			Constructor   = " ",
			Control       = " ",
			Copilot       = " ",
			Date          = "󱨰 ",
			DateTime      = "󱛡 ",
			Enum          = " ",
			EnumMember    = " ",
			Event         = " ",
			Field         = " ",
			File          = " ",
			Folder        = " ",
			Function      = "󰊕 ",
			Interface     = " ",
			Key           = " ",
			Keyword       = "󰌋 ",
			Label         = "󰀬 ",
			Method        = "󰊕 ",
			Module        = " ",
			Namespace     = "󰦮 ",
			Null          = "󰟢 ",
			Number        = " ",
			Object        = " ",
			Operator      = "󰆕 ",
			Package       = " ",
			Property      = " ",
			Reference     = " ",
			Snippet       = " ",
			String        = " ",
			Struct        = "󰆼 ",
			Supermaven    = " ",
			TabNine       = "󰏚 ",
			Text          = " ",
			TypeParameter = " ",
			Unit          = " ",
			Value         = " ",
			Variable      = "󰀫 ",
		},
	},
}

Config.stats = require("config.stats")

Config = vim.tbl_extend("error", Config, require("config.util"))

-- TODO: Figure out where this should go
Config.add("nvim-lua/plenary.nvim")

---@type Config
_G.Config = Config

require("config.ui")
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.folding")

return Config
