# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.smartdots]
local = "~/.config/sheldon/local/smartdots"

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins."z.lua"]
github = "skywind3000/z.lua"

[plugins.fnm]
inline = 'zsh-defer -1 -2 eval "$(fnm env --use-on-cd --version-file-strategy recursive)"'

[plugins.yarn]
github = "g-plane/zsh-yarn-autocompletions"
apply = ["install-yarn-autocompletions", "defer"]

[plugins.rust]
github = "cowboyd/zsh-rust"
apply = ["defer"]

[plugins.poetry]
github = "darvid/zsh-poetry"
apply = ["defer"]

[plugins.luaver]
github = "DhavalKapil/luaver"
apply = ["defer"]

# NOTE: fzf-tab needs to be loaded before plugins which will wrap widgets,
# such as zsh-autosuggestions or fast-syntax-highlighting!!
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.compinit]
local = "~/.config/sheldon/local/compinit"
apply = ["defer"]

# Uncomment to profile startup time.
# [plugins.zprof]
# inline = 'zmodload zsh/zprof && zsh-defer -1 -2 zprof'

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
# TODO: Figure out how to run this on install AND updates
install-yarn-autocompletions = { value = 'if [ ! -f "{{ dir }}/yarn-autocompletions" ]; then cd "{{ dir }}"; source ./zplug.zsh; cd -; fi', each = false }
