# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.smartdots]
local = "~/.config/sheldon/local/smartdots"

[plugins.workon]
local = "~/.config/sheldon/local/workon"

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.fnm]
inline = 'zsh-defer eval "$(fnm env --use-on-cd)"'

[plugins.zoxide]
inline = 'zsh-defer eval "$(zoxide init zsh)"'

[plugins.rust]
github = "cowboyd/zsh-rust"
apply = ["defer"]

[plugins.pyenv]
inline = 'zsh-defer eval "$(pyenv init --path --no-rehash)"'

[plugins.poetry]
github = "darvid/zsh-poetry"
apply = ["defer"]

[plugins.luaver]
github = "DhavalKapil/luaver"
apply = ["defer"]

# NOTE: fzf-tab needs to be loaded before plugins which will wrap widgets,
# such as zsh-autosuggestions or fast-syntax-highlighting!!
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

### completion

# NOTE: install-completions plugins should run before compinit!
[plugins.install-completions]
local = "~/.config/sheldon/local/install-completions"

[plugins.graphite-completions]
inline = 'install-completions graphite gt completion'

[plugins.yarn-completions]
github = "chrisands/zsh-yarn-completions"
use = ["zsh-yarn-completions.zsh"]
apply = ["install-yarn-completions"]

[plugins.compinit]
local = "~/.config/sheldon/local/compinit"

### tab title
[plugins.tab-title]
local = "~/.config/sheldon/local/tab-title"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
install-yarn-completions = """{% for file in files %}
install-completions {{ name }} <<-EOF\n#compdef yarn\nsource {{ file }}\nEOF
{% endfor %}"""
