# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.local]
local = "~/.config/sheldon/local"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.nvm]
github = "lukechilds/zsh-nvm"
apply = ["defer"]

[plugins.rust]
github = "cowboyd/zsh-rust"
apply = ["defer"]

[plugins.poetry]
github = "darvid/zsh-poetry"
apply = ["defer"]

# NOTE: fzf-tab needs to be loaded before plugins which will wrap widgets,
# such as zsh-autosuggestions or fast-syntax-highlighting!!
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
