return {
  {
    "LazyVim/LazyVim",
    ---@class LazyVimConfig
    opts = {
      filetypes = {
        ui = {
          "DiffviewFiles",
          "NvimTree",
          "Outline",
          "PlenaryTestPopup",
          "TelescopePrompt",
          "Trouble",
          "WhichKey",
          "alpha",
          "checkhealth",
          "cmp_menu",
          "dap-repl",
          "dap-view",
          "dap-view-repl",
          "dap-view-term",
          "dashboard",
          "dbout",
          "fugitive",
          "gitsigns-blame",
          "grug-far",
          "help",
          "lazy",
          "lspinfo",
          "man",
          "mason",
          "minifiles",
          "minipick",
          "ministarter",
          "neo-tree",
          "neo-tree-popup",
          "neotest-output",
          "neotest-output-panel",
          "neotest-summary",
          "noice",
          "notify",
          "oil",
          "oil_preview",
          "oil_progress",
          "packer",
          "qf",
          "sidekick_terminal",
          "snacks_dashboard",
          "snacks_notif",
          "snacks_picker",
          "snacks_picker_list",
          "snacks_terminal",
          "snacks_win",
          "spectre_panel",
          "startify",
          "startuptime",
          "terminal",
          "toggleterm",
          "trouble",
          "tsplayground",
          "unite",
          "wayfinder",
        },
      },
      icons = {
        separator = "  ",
        dots = "󰇘",
        prompt = "  ",
        caret = " ",
        multi = " ",
        eob = " ",
        tag = "󰓹 ",
        fold = {
          foldclose = "",
          foldopen = "",
          fold = " ",
          foldsep = " ",
        },
        diagnostics = {
          Error = " ",
          Warn = " ",
          Hint = " ",
          Info = " ",
        },
        diff = {
          added = " ",
          modified = " ",
          removed = " ",
        },
        git = {
          staged = " ",
          added = "󰐕 ",
          deleted = " ",
          ignored = " ",
          modified = " ",
          renamed = " ",
          unmerged = " ",
          untracked = " ",
        },
        task = {
          todo = "󰄰 ",
          done = "󰄴 ",
          active = "󰪞 ",
          cancelled = "󱃓 ",
          important = "󰗖 ",
        },
        services = {
          copilot = " ",
          diagnostics = "󱤧 ",
          formatting = "󰉼 ",
          not_persisting = " ",
          persisting = "󰅟 ",
          treesitter = " ",
        },
        kinds = {
          Copilot = " ",
          Date = "󱨰 ",
          DateTime = "󱛡 ",
          Event = " ",
          Keyword = "󰌋 ",
          Label = "󰀬 ",
          Null = "󰟢 ",
          Number = " ",
          Operator = "󰆕 ",
          Package = " ",
          Snippet = " ",
          String = " ",
          Text = " ",
        },
      },
    },
  },
}
