#!/usr/bin/env zsh
#
# Sourced from .zshrc
#

# prompt
zstyle :prompt:pure:git:stash show yes
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

# vi-style editor modes
zinit snippet OMZ::plugins/vi-mode

# Completions
zinit ice blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions
autoload compinit
compinit

# Allow running programs and scripts without adding anything to $PATH
zinit light zinit-zsh/z-a-bin-gem-node

# Allow packs to apply patches to installs.
# This is required by the fzf pack.
zinit light zinit-zsh/z-a-patch-dl

# BurntSushi/ripgrep
zinit ice from"gh-r" mv"ripgrep* -> rg" sbin"rg/rg"
zinit light BurntSushi/ripgrep

# fzf
export FZF_DEFAULT_OPTS="--layout reverse --info inline --height 40%"
export FZF_CTRL_T_OPTS="--preview \"bat --style=numbers --color=always --line-range :500 {}\""
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_OPTS="--preview \"bat --style=numbers --color=always --line-range :500 {}\""
zinit pack"bgn-binary+keys" for fzf
# NOTE: fzf-tab needs to be loaded after compinit, but before plugins which will wrap widgets, such as zsh-autosuggestions or fast-syntax-highlighting!!
zinit ice wait lucid
zinit light Aloxaf/fzf-tab
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf --preview 'exa -1 --color=always $realpath'
# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'
# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf --preview \
  '[[ $group == "[process ID]" ]] && ps --pid=$word -o cmd --no-headers -w -w'
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-flags --preview-window=down:3:wrap

# Autosuggestions
zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# tell me when i could've typed less.
zinit ice wait lucid load djui/alias-tips

# 'Smart' auto-close, delete and skips over matching delimiters
zinit ice wait lucid load hlissner/zsh-autopair

# History
zinit ice wait lucid snippet PZT::modules/history

# Syntax higlighting
zinit ice from"gh" wait lucid atinit"zpcompinit; zpcdreplay"
zinit light zdharma/fast-syntax-highlighting

## A way to do bash-style history ignore for certain commands
HISTORY_IGNORE="&:k:cd:ls:ll:la:l1:l.:..::pwd:exit:clear:cls"
zinit snippet PZT::modules/history

# System clipboard integration
zinit snippet OMZ::lib/clipboard.zsh

# Directory and cd
zinit snippet PZT::modules/directory

# sharkdp/fd, replacement for find
zinit ice wait lucid from"gh-r" mv"fd* -> fd" sbin"fd/fd"
zinit light sharkdp/fd

# sharkdp/bat, replacement for cat
zinit ice wait lucid from"gh-r" mv"bat* -> bat" sbin"bat/bat"
zinit light sharkdp/bat

# ogham/exa, replacement for ls
zinit ice wait lucid from"gh-r" mv"exa* -> exa" sbin"bin/exa"
zinit light ogham/exa

# dandavison/delta, replacement for diff
zinit ice wait lucid from"gh-r" mv"delta* -> delta" sbin"delta/delta"
zinit light dandavison/delta

# Node ecosystem
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true
zinit light lukechilds/zsh-nvm
zinit wait lucid for \
  lukechilds/zsh-better-npm-completion \
  atload"zpcdreplay" atclone'./zplug.zsh' g-plane/zsh-yarn-autocompletions

# Docker ecosystem
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
zinit wait lucid has'docker' for \
  as'completion' is-snippet 'https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker' \
  as'completion' is-snippet 'https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose'

# Rust ecosystem
zinit wait lucid for \
  cowboyd/zsh-rust \
  ryutok/rust-zsh-completions
