#!/usr/bin/env zsh
#
# Sourced from .zshrc
#

# Set the list of directories that Zsh searches for programs.
# We include common node_modules/.bin locations for convenience.
path=(
  {.,$HOME}/node_modules/.bin
  /usr/local/share/npm/bin
  $HOME/{bin,sbin}
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  /opt/X11/bin
)

# prompt
zstyle :prompt:pure:git:stash show yes
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

# vi-style editor modes
zinit snippet OMZ::plugins/vi-mode

# Completions
zinit ice blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions
autoload compinit
compinit

# Autocorrect
setopt correct
# theoretically helpful correction is too frequently just annoying :(
# To help reduce annoying false corrections, we keep a .znocorrect file.
# Any commands listed in that file will not be corrected.
if [ -f ~/.znocorrect ]; then
  while read -r COMMAND; do
    alias $COMMAND="nocorrect $COMMAND"
  done < ~/.znocorrect
fi

# fzf
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --ansi --height=40%"
zinit ice wait lucid from"gh-r" as"program" mv"fzf* -> fzf"
zinit light junegunn/fzf-bin

# Autosuggestions
zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# tell me when i could've typed less.
zinit ice wait lucid load djui/alias-tips

# 'Smart' auto-close, delete and skips over matching delimiters
zinit ice wait lucid load hlissner/zsh-autopair

# History search. Note: this must be loaded before syntax highlighting
zinit ice wait lucid load zsh-users/zsh-history-substring-search
zinit ice wait lucid snippet PZT::modules/history

# Syntax higlighting
zinit ice wait lucid load zdharma/fast-syntax-highlighting

# A way to do bash-style history ignore for certain commands
HISTIGNORE="&:k:cd:ls:ll:la:l1:l.:..::pwd:exit:clear:cls"
function zshaddhistory() {
  CMDS=("${(s/:/)HISTIGNORE}")
  for CMD in $CMDS; do
    if [[ $1 == "$CMD"* ]] ; then
        return 1
    fi
  done
}

# System clipboard integration
zinit snippet OMZ::lib/clipboard.zsh

# Directory and cd
zinit snippet PZT::modules/directory
zinit light b4b4r07/enhancd
export ENHANCD_FILTER="fzf:peco"
export ENHANCD_DOT_SHOW_FULLPATH=1

# ogham/exa, replacement for ls
zinit ice wait lucid from"gh-r" as"program" mv"exa* -> exa" pick"bin/exa"
zinit light ogham/exa

# Node ecosystem
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true
zinit wait lucid for \
  lukechilds/zsh-nvm \
  lukechilds/zsh-better-npm-completion \
  atload"zpcdreplay" atclone'./zplug.zsh' g-plane/zsh-yarn-autocompletions

# Docker ecosystem
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
zinit wait lucid has'docker' for \
  as'completion' is-snippet 'https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker' \
  as'completion' is-snippet 'https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose'

# Rust ecosystem
zinit wait lucid for \
  cowboyd/zsh-rust \
  ryutok/rust-zsh-completions
