#!/usr/bin/env zsh
#
# Executes commands at login pre-zshrc.
#
# Adapted from the prezto/runcoms/zprofile

# Don't load global configs, i.e., /etc/zprofile, /etc/zshrc
setopt no_global_rcs

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ ! -z "$ONIVIM_TERMINAL" ]]; then
  export EDITOR='oni2 --nofork --silent'
  export VISUAL='oni2 --nofork --silent'
elif [[ "$TERM_PROGRAM" == "vscode" ]]; then
  export EDITOR='code --wait'
  export VISUAL='code --wait'
elif [[ $+commands[nvim] ]]; then
  export VISUAL=nvim
  export EDITOR=$VISUAL
else
  export VISUAL='vim'
  export EDITOR=$VISUAL
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
# We include common node_modules/.bin locations for convenience.
path=(
  {.,$HOME}/node_modules/.bin
  /usr/local/share/npm/bin
  $HOME/.zinit/polaris/bin
  $HOME/{bin,sbin}
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  /opt/X11/bin
)
